environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci\\appveyor\\run_with_env.cmd"

  matrix:
    - PYTHON: "C:\\Python35_64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      CONDA_PY: "35"
      CONDA_NPY: "18"
      QTDIR: "C:\\Qt\\5.6\\msvc2015_64"
      platform: x64

    - PYTHON: "C:\\Python35_32"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      CONDA_PY: "35"
      CONDA_NPY: "18"
      QTDIR: "C:\\Qt\\5.6\\msvc2015"
      platform: x86

install:
  # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit),
  # as well as pip, conda-build, and the binstar CLI
  - powershell .\\ci\\appveyor\\install.ps1

  #- dir /b /s /ad c:\Qt\5.6
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # Add qt to path
  - "SET PATH=%QTDIR%\\bin;%QTDIR%\\lib;%PATH%"
  - "SET QT_PLUGIN_PATH=%QTDIR%\\plugins"
  - echo %PATH%
  #- choco install -y vcredist2015
  - "%CMD_IN_ENV% conda config --set always_yes yes --set changeps1 no"
  - "%CMD_IN_ENV% conda config --add channels inso/channel/sakia"
  - "%CMD_IN_ENV% conda create -q -n test-environment python=%PYTHON_VERSION% pyqt5=5.6 libsodium=1.0.3 setuptools=19.2"

build_script:
  - ".\\ci\\appveyor\\build.cmd"

#test_script:
  - ".\\ci\\appveyor\\tests.cmd"
  - echo %errorlevel%

  - powershell .\\ci\\appveyor\\download_vcredist.ps1 -target %cd%\\ci\\appveyor

  # Windows Installer
  - choco install -y InnoSetup
  - set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%
  - iscc %cd%\ci\appveyor\sakia.iss /DROOT_PATH=%cd%
  - move %cd%\sakia.exe %cd%\sakia-%APPVEYOR_REPO_TAG_NAME%-win%PYTHON_ARCH%.exe

artifacts:
  - path: dist
    name: sakia-win$(PYTHON_ARCH)
  - path: sakia*.exe
    name: sakia-exe
# upload to releases
deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: sakia $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: wbzlh6nx1zY1J1avlB0C3hKGm1abFNHBdM60u/U09i5Nam//D6kazvnv5ZBKdR89
  artifact: /sakia-/
  draft: true
  prerelease: true
  on:
    appveyor_repo_tag: true

